
work_dir: ./work_dir/zjlab_action/msg3d_bone

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: /data1/zhumh/zjlab_actions/train_data/train_data_bone.npy
  label_path: /data1/zhumh/zjlab_actions/train_data/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 20
  normalization: False

test_feeder_args:
  data_path: /data1/zhumh/zjlab_actions/train_data/val_data_bone.npy
  label_path: /data1/zhumh/zjlab_actions/train_data/val_label.pkl

# model
model: model.msg3d.Model
model_args:
  num_class: 9
  num_point: 18
  num_person: 2
  num_gcn_scales: 8
  num_g3d_scales: 8
  graph: graph.zjlab_action.AdjMatrixGraph

# optim
# TODO: check the hyperparams
weight_decay: 0.0005
base_lr: 0.01
step: [45, 55]

# training
num_epoch: 65
device: [7]
batch_size: 32
forward_batch_size: 16
test_batch_size: 32
nesterov: True




